#!/usr/bin/env python3
"""Export ALL Expo historical theaters into unity/Genesis StreamingAssets.

Sources:
  - src/data/historical/catalog.ts (+ extraPartitionTheaters.ts)
  - src/data/theaterTemplates.ts (markers / corridors / zones by archetype)
  - src/maps/geoAtlas.ts (board-space land rings / cities / borders)
  - Optional Natural Earth silhouettes under StreamingAssets/Maps/geo/*.json
    (generated by scripts/generate-unity-map-assets.py)
"""
from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "src/data/historical/catalog.ts"
EXTRAS = ROOT / "src/data/historical/extraPartitionTheaters.ts"
TEMPLATES = ROOT / "src/data/theaterTemplates.ts"
GEO = ROOT / "src/maps/geoAtlas.ts"
OUT = ROOT / "unity/Genesis/Assets/StreamingAssets/Theaters"
MAPS_OUT = ROOT / "unity/Genesis/Assets/StreamingAssets/Maps"
ASSETS_MAPS = ROOT / "assets/maps"
NE_GEO = MAPS_OUT / "geo"

ARCHETYPE_TO_TEMPLATE = {
    "pacific": "pacific",
    "sahel": "sahel",
    "redsea": "redsea",
    "americas": "americas",
    "southasia": "southasia",
    "markets": "markets",
    "arctic": "arctic",
    "gulf": "gulf",
    "europe": "europe",
}

# Prefer Natural Earth hero rings when present (region id → file stem).
NE_REGION_FILES = {
    "southasia": "southasia",
    "caribbean": "caribbean",
    "korea": "korea",
    "gulf": "gulf",
    "manchuria": "manchuria",
    "europe-central": "europe-central",
    "europe-west": "europe-west",
    "europe-east": "europe-east",
    "russia-west": "russia-west",
    "pacific-japan": "pacific-japan",
    "china-east": "china-east",
    "suez": "suez",
    "levant": "levant",
    "anatolia": "anatolia",
    "black-sea": "black-sea",
    "afghanistan": "afghanistan",
    "se-asia": "se-asia",
    "poland-corridor": "poland-corridor",
    "pacific-hawaii": "pacific-hawaii",
    "berlin": "berlin",
    "atlantic-finance": "atlantic-finance",
    "maghreb-east": "maghreb-east",
    "world-hubs": "world-hubs",
}


def extract_by_id(src: str, sid: str) -> str:
    needle = f"id: '{sid}'"
    idx = src.find(needle)
    if idx < 0:
        raise SystemExit(f"missing {sid}")
    start = src.rfind("{", 0, idx)
    depth = 0
    for i, c in enumerate(src[start:], start):
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return src[start : i + 1]
    raise SystemExit(f"unbalanced {sid}")


def field(s: str, name: str):
    m = re.search(rf"{name}:\s*'((?:\\'|[^'])*)'", s)
    if m:
        return m.group(1).replace("\\'", "'")
    m = re.search(rf"{name}:\s*(-?\d+)", s)
    if m:
        return int(m.group(1))
    return None


def parse_choices(beat_src: str):
    cm = re.search(r"choices:\s*\[", beat_src)
    if not cm:
        return []
    rest = beat_src[cm.end() - 1 :]
    depth = 0
    end = None
    for i, c in enumerate(rest):
        if c == "[":
            depth += 1
        elif c == "]":
            depth -= 1
            if depth == 0:
                end = i
                break
    arr = rest[1:end]
    choices = []
    depth = 0
    start = None
    for i, c in enumerate(arr):
        if c == "{":
            if depth == 0:
                start = i
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0 and start is not None:
                csrc = arr[start : i + 1]

                def cf(n):
                    m = re.search(rf"{n}:\s*'((?:\\'|[^'])*)'", csrc)
                    return m.group(1).replace("\\'", "'") if m else ""

                effects = []
                em = re.search(r"effects:\s*\[", csrc)
                if em:
                    er = csrc[em.end() - 1 :]
                    d = 0
                    eend = None
                    for j, ch in enumerate(er):
                        if ch == "[":
                            d += 1
                        elif ch == "]":
                            d -= 1
                            if d == 0:
                                eend = j
                                break
                    earr = er[1:eend]
                    d = 0
                    st = None
                    for j, ch in enumerate(earr):
                        if ch == "{":
                            if d == 0:
                                st = j
                            d += 1
                        elif ch == "}":
                            d -= 1
                            if d == 0 and st is not None:
                                es = earr[st : j + 1]

                                def ef(n):
                                    m = re.search(rf"{n}:\s*'((?:\\'|[^'])*)'", es)
                                    if m:
                                        return m.group(1).replace("\\'", "'")
                                    m = re.search(rf"{n}:\s*(-?\d+)", es)
                                    if m:
                                        return int(m.group(1))
                                    return None

                                effects.append(
                                    {
                                        "tag": ef("tag"),
                                        "weight": ef("weight"),
                                        "summary": ef("summary"),
                                    }
                                )
                                st = None
                choice = {
                    "id": cf("id"),
                    "label": cf("label"),
                    "detail": cf("detail"),
                    "kind": cf("kind"),
                    "markerId": cf("markerId"),
                    "short": cf("short"),
                    "callsign": cf("callsign"),
                    "effects": effects,
                }
                choices.append(choice)
                start = None
    return choices


def parse_scenario(sid: str, src: str):
    s = extract_by_id(src, sid)
    obj = {
        k: field(s, k)
        for k in [
            "id",
            "year",
            "era",
            "title",
            "region",
            "meterFamily",
            "theaterArchetype",
            "premise",
            "role",
            "tension",
        ]
    }
    beats_m = re.search(r"beats:\s*\[", s)
    rest = s[beats_m.end() - 1 :]
    depth = 0
    end = None
    for i, c in enumerate(rest):
        if c == "[":
            depth += 1
        elif c == "]":
            depth -= 1
            if depth == 0:
                end = i
                break
    beats_src = rest[1:end]
    beat_blocks = []
    depth = 0
    start = None
    for i, c in enumerate(beats_src):
        if c == "{":
            if depth == 0:
                start = i
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0 and start is not None:
                beat_blocks.append(beats_src[start : i + 1])
                start = None
    beats = []
    for bsrc in beat_blocks:

        def bf(n):
            m = re.search(rf"{n}:\s*'((?:\\'|[^'])*)'", bsrc)
            return m.group(1).replace("\\'", "'") if m else ""

        beats.append(
            {
                "id": bf("id"),
                "title": bf("title"),
                "briefing": bf("briefing"),
                "stakes": bf("stakes"),
                "choices": parse_choices(bsrc),
            }
        )
    obj["beats"] = beats
    return obj


def list_scenario_ids(*sources: str) -> list[str]:
    ids = []
    seen = set()
    for src in sources:
        for m in re.finditer(
            r"\{\s*\n\s+id: '(hist-[^']+)',\s*\n\s+year:\s*\d+",
            src,
        ):
            sid = m.group(1)
            if sid not in seen:
                seen.add(sid)
                ids.append(sid)
    return ids


def enrich(sc: dict) -> dict:
    """Fill missing callsign / short from label; keep catalog kind/markerId."""
    for beat in sc.get("beats", []):
        for ch in beat.get("choices", []):
            words = [w for w in re.split(r"\W+", ch.get("label") or "") if w]
            if not ch.get("callsign"):
                ch["callsign"] = " ".join(words[:2]).upper() if words else "ORDER"
            if not ch.get("short"):
                ch["short"] = (words[0].upper() if words else "ORDER")[:10]
            if not ch.get("kind"):
                ch["kind"] = "diplomatic"
            if not ch.get("markerId"):
                ch["markerId"] = "loc"
    return sc


def parse_markers(block: str):
    markers = [
        {
            "id": m.group(1),
            "label": m.group(2),
            "x": float(m.group(3)),
            "y": float(m.group(4)),
            "kind": m.group(5),
        }
        for m in re.finditer(
            r"\{\s*id:\s*'([^']+)',\s*label:\s*'([^']+)',\s*x:\s*([\d.]+),\s*y:\s*([\d.]+),\s*kind:\s*'([^']+)'\s*\}",
            block,
        )
    ]
    corridors = [
        {"from": m.group(1), "to": m.group(2)}
        for m in re.finditer(r"\{\s*from:\s*'([^']+)',\s*to:\s*'([^']+)'\s*\}", block)
    ]
    zones = [
        {
            "id": m.group(1),
            "label": m.group(2),
            "x": float(m.group(3)),
            "y": float(m.group(4)),
            "w": float(m.group(5)),
            "h": float(m.group(6)),
            "tension": float(m.group(7)),
        }
        for m in re.finditer(
            r"\{\s*id:\s*'([^']+)',\s*label:\s*'([^']+)',\s*x:\s*([\d.]+),\s*y:\s*([\d.]+),\s*w:\s*([\d.]+),\s*h:\s*([\d.]+),\s*tension:\s*([\d.]+)\s*\}",
            block,
        )
    ]
    return markers, corridors, zones


def parse_templates(tmpl_src: str) -> dict:
    """archetype → template block fields."""
    out = {}
    for arch in ARCHETYPE_TO_TEMPLATE:
        m = re.search(rf"archetype:\s*'{arch}'", tmpl_src)
        if not m:
            continue
        start = tmpl_src.rfind("{", 0, m.start())
        depth = 0
        block = None
        for i, c in enumerate(tmpl_src[start:], start):
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    block = tmpl_src[start : i + 1]
                    break
        if not block:
            continue
        markers, corridors, zones = parse_markers(block)
        out[arch] = {
            "id": field(block, "id") or arch,
            "defaultTitle": field(block, "defaultTitle") or arch.upper(),
            "subtitle": field(block, "subtitle") or "",
            "water": field(block, "water") or "#0A2434",
            "land": field(block, "land") or "#1E3340",
            "accent": field(block, "accent") or "#D4A04A",
            "markers": markers,
            "corridors": corridors,
            "zones": zones,
        }
    return out


def parse_scenario_geo_map(geo_text: str) -> dict[str, str]:
    m = re.search(r"SCENARIO_GEO:\s*Record<string,\s*string>\s*=\s*\{([^}]+)\}", geo_text)
    if not m:
        return {}
    return {
        a: b
        for a, b in re.findall(r"'([^']+)':\s*'([^']+)'", m.group(1))
    }


def extract_geo_region(geo_text: str, region_id: str) -> dict | None:
    # Match both quoted and bare keys: 'europe-central': {  OR southasia: {
    patterns = [
        rf"'{re.escape(region_id)}'\s*:\s*\{{",
        rf"(?<![\w-]){re.escape(region_id)}\s*:\s*\{{",
    ]
    idx = -1
    for pat in patterns:
        m = re.search(pat, geo_text)
        if m:
            idx = m.end() - 1
            break
    if idx < 0:
        return None
    depth = 0
    geo_block = None
    for i, c in enumerate(geo_text[idx:], idx):
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                geo_block = geo_text[idx : i + 1]
                break
    if not geo_block:
        return None

    def rings_after(key: str):
        rings = []
        km = re.search(rf"{key}:\s*\[", geo_block)
        if not km:
            return rings
        rest = geo_block[km.end() - 1 :]
        depth = 0
        end = None
        for i, c in enumerate(rest):
            if c == "[":
                depth += 1
            elif c == "]":
                depth -= 1
                if depth == 0:
                    end = i
                    break
        body = rest[1:end]
        for poly_m in re.finditer(r"\[\s*((?:\[[\d.]+,\s*[\d.]+\]\s*,?\s*)+)\]", body):
            pts = [
                [float(a), float(b)]
                for a, b in re.findall(r"\[([\d.]+),\s*([\d.]+)\]", poly_m.group(1))
            ]
            if pts:
                rings.append(pts)
        return rings

    cities = [
        {"name": m.group(1), "x": float(m.group(2)), "y": float(m.group(3))}
        for m in re.finditer(
            r"\{\s*name:\s*'([^']+)',\s*x:\s*([\d.]+),\s*y:\s*([\d.]+)\s*\}",
            geo_block,
        )
    ]
    return {
        "id": field(geo_block, "id") or region_id,
        "label": field(geo_block, "label") or region_id,
        "water": field(geo_block, "water") or "#0A2434",
        "land": field(geo_block, "land") or "#2A3A24",
        "landHi": field(geo_block, "landHi") or "#3A4A34",
        "accent": field(geo_block, "accent") or "#D4A04A",
        "lands": rings_after("lands"),
        "borders": rings_after("borders"),
        "rivers": rings_after("rivers"),
        "cities": cities,
    }


def load_ne_overlay(region_id: str) -> dict | None:
    stem = NE_REGION_FILES.get(region_id)
    if not stem:
        return None
    path = NE_GEO / f"{stem}.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text())
    except Exception:
        return None


def merge_geo(atlas: dict | None, ne: dict | None) -> dict:
    """Prefer Natural Earth land rings when denser; keep atlas cities/borders."""
    base = atlas or {
        "id": "fallback",
        "label": "Theater",
        "water": "#0A2434",
        "land": "#2A3A24",
        "landHi": "#3A4A34",
        "accent": "#D4A04A",
        "lands": [],
        "borders": [],
        "rivers": [],
        "cities": [],
    }
    if not ne:
        return base
    merged = dict(base)
    ne_lands = ne.get("lands") or []
    if ne_lands and (
        not base.get("lands")
        or sum(len(r) for r in ne_lands) > sum(len(r) for r in base.get("lands") or [])
    ):
        merged["lands"] = ne_lands
        merged["source"] = "natural-earth+atlas"
    else:
        merged["source"] = "atlas"
    if ne.get("cities") and (not base.get("cities") or len(ne["cities"]) >= len(base["cities"])):
        # Keep atlas city names (game content) but allow NE to fill gaps.
        merged["cities"] = base.get("cities") or ne["cities"]
    if ne.get("borders") and not base.get("borders"):
        merged["borders"] = ne["borders"]
    if ne.get("label"):
        merged["label"] = ne["label"]
    return merged


def terrain_key_for(archetype: str, region_id: str) -> str:
    """Map to assets/maps/terrain_*.jpg keys."""
    if region_id in ("southasia",):
        return "southasia"
    if region_id in ("caribbean",):
        return "americas"
    if region_id in ("korea", "manchuria", "pacific-hawaii", "pacific-japan", "china-east", "se-asia"):
        return "pacific"
    if region_id in ("gulf",):
        return "gulf"
    if region_id in ("suez", "levant", "anatolia", "maghreb-east"):
        return "redsea"
    if region_id in ("afghanistan",):
        return "sahel"
    if region_id in ("atlantic-finance",):
        return "markets"
    if archetype in ARCHETYPE_TO_TEMPLATE:
        key = ARCHETYPE_TO_TEMPLATE[archetype]
        if key == "arctic":
            return "arctic"
        if key in ("pacific", "sahel", "redsea", "americas", "southasia", "markets", "gulf", "europe"):
            return key
    return "europe"


def build_board(sc: dict, templates: dict, geo_map: dict, geo_text: str) -> dict:
    arch = sc.get("theaterArchetype") or "europe"
    tmpl = templates.get(arch) or templates.get("europe") or next(iter(templates.values()))
    region_id = geo_map.get(sc["id"]) or {
        "pacific": "manchuria",
        "sahel": "afghanistan",
        "redsea": "suez",
        "americas": "caribbean",
        "southasia": "southasia",
        "markets": "atlantic-finance",
        "arctic": "europe-central",
        "gulf": "gulf",
        "europe": "europe-central",
    }.get(arch, "europe-central")

    atlas = extract_geo_region(geo_text, region_id)
    ne = load_ne_overlay(region_id)
    geo = merge_geo(atlas, ne)
    terrain = terrain_key_for(arch, region_id)

    title = (tmpl.get("defaultTitle") or sc.get("title") or "THEATER").upper()[:28]
    if sc.get("id") == "hist-1947-radcliffe":
        title = "PARTITION LINE"
    elif sc.get("id") == "hist-1962-cuba":
        title = "THIRTEEN DAYS"

    return {
        "id": geo.get("id") or region_id,
        "scenarioId": sc["id"],
        "title": title,
        "subtitle": tmpl.get("subtitle") or sc.get("region") or "",
        "water": geo.get("water") or tmpl.get("water"),
        "land": geo.get("land") or tmpl.get("land"),
        "accent": geo.get("accent") or tmpl.get("accent"),
        "markers": tmpl.get("markers") or [],
        "corridors": tmpl.get("corridors") or [],
        "zones": tmpl.get("zones") or [],
        "terrainKey": terrain,
        "geo": {
            "label": geo.get("label") or region_id,
            "water": geo.get("water"),
            "land": geo.get("land"),
            "landHi": geo.get("landHi"),
            "accent": geo.get("accent"),
            "source": geo.get("source", "atlas"),
            "terrainKey": terrain,
            "reliefKey": terrain,
            "lands": geo.get("lands") or [],
            "borders": geo.get("borders") or [],
            "rivers": geo.get("rivers") or [],
            "cities": geo.get("cities") or [],
        },
    }


def copy_terrain_assets():
    MAPS_OUT.mkdir(parents=True, exist_ok=True)
    terrain_dir = MAPS_OUT / "terrain"
    terrain_dir.mkdir(parents=True, exist_ok=True)
    if not ASSETS_MAPS.exists():
        return
    for src in ASSETS_MAPS.glob("terrain_*.jpg"):
        dst = terrain_dir / src.name
        shutil.copy2(src, dst)


def write_meta_for_json(path: Path):
    meta = path.with_suffix(path.suffix + ".meta")
    if meta.exists():
        return
    # Stable-ish guid from path hash
    import hashlib

    g = hashlib.md5(str(path.relative_to(ROOT)).encode()).hexdigest()
    meta.write_text(
        "fileFormatVersion: 2\n"
        f"guid: {g}\n"
        "DefaultImporter:\n"
        "  externalObjects: {}\n"
        "  userData: \n"
        "  assetBundleName: \n"
        "  assetBundleVariant: \n"
    )


def main():
    catalog_src = CATALOG.read_text()
    extras_src = EXTRAS.read_text() if EXTRAS.exists() else ""
    tmpl_src = TEMPLATES.read_text()
    geo_text = GEO.read_text()
    OUT.mkdir(parents=True, exist_ok=True)

    templates = parse_templates(tmpl_src)
    geo_map = parse_scenario_geo_map(geo_text)
    # Extras may not be in SCENARIO_GEO — add defaults.
    geo_map.setdefault("hist-1917-balfour", "levant")
    geo_map.setdefault("hist-1948-two-koreas", "korea")

    ids = list_scenario_ids(catalog_src, extras_src)
    # Sort by year then id using parsed scenarios.
    scenarios = []
    for sid in ids:
        src = catalog_src if f"id: '{sid}'" in catalog_src else extras_src
        sc = enrich(parse_scenario(sid, src))
        scenarios.append(sc)
    scenarios.sort(key=lambda s: (s.get("year") or 0, s.get("id") or ""))

    copy_terrain_assets()

    catalog_entries = []
    for sc in scenarios:
        board = build_board(sc, templates, geo_map, geo_text)
        payload = {"scenario": sc, "board": board}
        out_path = OUT / f"{sc['id']}.json"
        out_path.write_text(json.dumps(payload, indent=2))
        write_meta_for_json(out_path)
        catalog_entries.append(
            {
                "id": sc["id"],
                "title": sc.get("title") or sc["id"],
                "year": sc.get("year") or 0,
                "era": sc.get("era") or "",
                "region": sc.get("region") or "",
                "archetype": sc.get("theaterArchetype") or "",
                "file": f"{sc['id']}.json",
                "terrainKey": board.get("terrainKey") or "europe",
                "free": sc["id"]
                in ("hist-1947-radcliffe", "hist-1962-cuba"),
            }
        )

    catalog = {
        "unityVersion": "6000.0.84f1",
        "sliceTheaterId": "hist-1947-radcliffe",
        "theaterCount": len(catalog_entries),
        "theaters": catalog_entries,
    }
    cat_path = OUT / "catalog.json"
    cat_path.write_text(json.dumps(catalog, indent=2))
    write_meta_for_json(cat_path)

    print(f"Exported {len(catalog_entries)} theaters → {OUT}")
    for e in catalog_entries:
        print(f"  {e['year']}  {e['id']}  ({e['archetype']})")


if __name__ == "__main__":
    main()
